networks:
  dev:
    driver: bridge

services:
  zettelkasten_api:
    container_name: zettelkasten
    image: ghcr.io/skey1234/zettelkasten:latest
    depends_on: 
      - "zettelkasten_db"
    ports:
      - 8990:8080
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=zettelkasten_db;Port=5432;Database=zettelkasten;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - dev

  zettelkasten_db:
    image: postgres:latest
    container_name: zettelkasten_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zettelkasten
    ports:
      - 5433:5432
    restart: always
    volumes:
      - zettelkasten_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  zettelkasten_data: